version: '3.1'

services:
  iridaDB:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'telegram_bot_irida'
      MYSQL_USER: 'bestuser'
      MYSQL_PASSWORD: 'bestuser'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  irida:
    depends_on:
      - iridaDB
    build:
      context: .
    environment:
      BOT_NAME: irida_recom_test_bot
      BOT_TOKEN: 5127901141:AAF_5wRZtWTYSZyyJT-5FkBNPQ9hI3ijgro
      SPRING_DATABASE_URL: jdbc:mysql://iridaDB:3306/telegram_bot_irida
      BOT_ADMIN: ZloyShafran
    restart: always