version: '3.1'

services:
  irida:
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: always
  iridaDB:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'telegram_bot_irida'
      MYSQL_USER: 'bestuser'
      MYSQL_PASSWORD: 'bestuser'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci